-- =============================================================================
-- PERMISSAO DA MANUTENCAO DO MANUAL  —  banco SQL Server do PCM
--
-- O conteudo do manual mora no PostgreSQL (Supabase), mas a permissao de quem
-- pode manter o manual segue o padrao do PCM: um formulario no cadastro de
-- perfis, consultado por sp_select_cadastro_basico_perfil_direito_dados com
-- formulario = 'adm_manual'.
--
-- Enquanto 'adm_manual' nao existir no cadastro de formularios, o sistema usa
-- como reserva o direito de 'adm_perfil' (quem administra perfis tambem pode
-- manter o manual). Ou seja: o manual ja funciona sem rodar este script; rode-o
-- quando quiser controlar o direito separadamente, perfil a perfil.
--
-- ATENCAO: os nomes de tabela abaixo sao um modelo — confira na sua base qual
-- tabela alimenta a sp_select_cadastro_basico_perfil_direito_dados (o cadastro
-- de formularios usado pela tela de Perfil) e ajuste antes de rodar.
-- =============================================================================

-- 1) Registra o formulario (ajuste o nome da tabela/colunas conforme sua base):
-- IF NOT EXISTS (SELECT 1 FROM cadastro_basico_formulario WHERE formulario = 'adm_manual')
--     INSERT INTO cadastro_basico_formulario (formulario, descricao, ativo)
--     VALUES ('adm_manual', 'Manual', 1);

-- 2) Concede o direito aos perfis administradores (ajuste conforme sua base):
-- INSERT INTO cadastro_basico_perfil_direito (codigo_empresa, codigo_perfil, codigo_formulario,
--                                             visualizar, inserir, editar, excluir, administrador)
-- SELECT d.codigo_empresa, d.codigo_perfil,
--        (SELECT codigo_formulario FROM cadastro_basico_formulario WHERE formulario = 'adm_manual'),
--        'S', 1, 1, 1, d.administrador
-- FROM   cadastro_basico_perfil_direito d
-- JOIN   cadastro_basico_formulario f ON f.codigo_formulario = d.codigo_formulario
-- WHERE  f.formulario = 'adm_perfil'
--   AND  NOT EXISTS (SELECT 1
--                    FROM  cadastro_basico_perfil_direito x
--                    JOIN  cadastro_basico_formulario xf ON xf.codigo_formulario = x.codigo_formulario
--                    WHERE xf.formulario = 'adm_manual'
--                      AND x.codigo_perfil = d.codigo_perfil
--                      AND x.codigo_empresa = d.codigo_empresa);
